// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaaiugsilaibnyfoggzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhYWl1Z3NpbGFpYm55Zm9nZ3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjUyNDMsImV4cCI6MjA3MTU0MTI0M30.msunAziEK31OxC_AETdjieLAjhEuByB8L5e7lUVM9_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});